import { Amethysta, Tenor_Sans } from "next/font/google";
import "./globals.css";
import React from 'react';

const amethysta = Amethysta({
    weight: ['400'],
    variable: "--font-amethysta",
    subsets: ["latin"],
});

const tenorSans = Tenor_Sans({
    weight: ['400'],
    variable: "--font-tenor-sans",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${amethysta.variable} ${tenorSans.variable}`}>
        {children}
        </body>
        </html>
    );
}